In [6]:
# Configure AWS profile for local development
%env AWS_PROFILE=platform-developer

from adapters.extractors.ebsco.helpers import build_adapter_table as build_adapter_table_ebsco
from adapters.extractors.oai_pmh.axiell.runtime import AXIELL_CONFIG
from adapters.extractors.oai_pmh.folio.runtime import FOLIO_CONFIG

# If false, use local Iceberg tables instead of the S3 Tables REST API
USE_REST_API_TABLE = True
# Separate kill switch for any helper that mutates table contents
ALLOW_REMOTE_TABLE_MUTATIONS = False

# Load the Iceberg tables
ebsco_adapter_table = build_adapter_table_ebsco(use_rest_api_table=USE_REST_API_TABLE)
axiell_adapter_table = AXIELL_CONFIG.build_adapter_table(use_rest_api_table=USE_REST_API_TABLE)
folio_adapter_table = FOLIO_CONFIG.build_adapter_table(use_rest_api_table=USE_REST_API_TABLE)

tables = {
    "ebsco_adapter_table": ebsco_adapter_table,
    "axiell_adapter_table": axiell_adapter_table,
    "folio_adapter_table": folio_adapter_table,
}

TABLE_NAMESPACES = {
    "ebsco_adapter_table": "ebsco",
    "axiell_adapter_table": AXIELL_CONFIG.config.adapter_namespace,
    "folio_adapter_table": FOLIO_CONFIG.config.adapter_namespace,
}

print("Adapter tables loaded")
print(
    "Target catalog: remote REST API" if USE_REST_API_TABLE else "Target catalog: local"
)
if USE_REST_API_TABLE and not ALLOW_REMOTE_TABLE_MUTATIONS:
    print(
        "Remote table mutation helpers are blocked. Set ALLOW_REMOTE_TABLE_MUTATIONS=True only for intentional remote changes."
    )

for table in tables.values():
    print(table)

env: AWS_PROFILE=platform-developer
Adapter tables loaded
Target catalog: remote REST API
Remote table mutation helpers are blocked. Set ALLOW_REMOTE_TABLE_MUTATIONS=True only for intentional remote changes.
ebsco_adapter_table(
  1: namespace: required string,
  2: id: required string,
  3: content: optional string,
  4: changeset: optional string,
  5: last_modified: optional timestamptz,
  6: deleted: optional boolean
),
partition by: [],
sort order: [2 ASC NULLS FIRST],
snapshot: Operation.APPEND: id=3806354529436074127, parent_id=8620739497634651949, schema_id=1
axiell_adapter_table(
  1: namespace: required string,
  2: id: required string,
  3: content: optional string,
  4: changeset: optional string,
  5: last_modified: optional timestamptz,
  6: deleted: optional boolean
),
partition by: [],
sort order: [2 ASC NULLS FIRST],
snapshot: Operation.APPEND: id=3819093019992084272, parent_id=8669021194990111422, schema_id=0
folio_adapter_table(
  1: namespace: required string,
  2: id: required string,
  3: content: optional string,
  4: changeset: optional string,
  5: last_modified: optional timestamptz,
  6: deleted: optional boolean
),
partition by: [],
sort order: [2 ASC NULLS FIRST],
snapshot: Operation.APPEND: id=8231165485606948402, parent_id=7230056817939218599, schema_id=0

In [4]:
# Summarise each adapter table: total records + earliest/latest last_modified
# Note: computing earliest/latest requires scanning the `last_modified` column and may take a while on large tables.

from __future__ import annotations

import pandas as pd
import pyarrow as pa
import pyarrow.compute as pc


def _table_summary(name: str, t):
    # Count is usually metadata-driven (fast-ish), but can still take time depending on table/files.
    count = t.scan().count()
    
    earliest = None
    latest = None
    try:
        lm = t.scan(selected_fields=("last_modified",)).to_arrow()["last_modified"]
        # Drop nulls if present
        earliest = pc.min(lm).as_py()
        latest = pc.max(lm).as_py()
    except Exception as e:
        print(f"Could not compute earliest/latest last_modified for {name}: {e}")
    
    return {
        "table": name,
        "records": count,
        "earliest_last_modified": earliest,
        "latest_last_modified": latest,
    }

summary_df = pd.DataFrame(
    [
        _table_summary(name, table) for name, table in tables.items()
    ]
).sort_values("table")

display(summary_df)

                  table  ...             latest_last_modified
1  axiell_adapter_table  ...        2026-05-07 16:03:38+00:00
0   ebsco_adapter_table  ... 2026-05-08 02:01:38.642847+00:00
2   folio_adapter_table  ...        2026-05-05 21:06:53+00:00

[3 rows x 4 columns]

In [5]:
from adapters.utils.schemata import ADAPTER_STORE_ARROW_SCHEMA

FIELD_NAMES = [field.name for field in ADAPTER_STORE_ARROW_SCHEMA]

def get_sample(table, limit = 20):
    # Retrieve the first N data rows (excluding any projection to keep all columns)
    first_n = table.scan(
        selected_fields=FIELD_NAMES,
        limit=limit,
    ).to_arrow()

    return first_n.to_pandas()


def get_record_by_id(table, record_id: str):
    record = table.scan(
        selected_fields=FIELD_NAMES,
        row_filter=f"id = '{record_id}'",
    ).to_arrow()
    
    return record


table_samples = {
    name: get_sample(table)
    for name, table in tables.items()
}

for name, sample in table_samples.items():
    print(name)
    display(sample)

ebsco_adapter_table

   namespace             id  ...                    last_modified deleted
0      ebsco  ebs115508527e  ... 2026-05-08 02:01:38.642847+00:00    None
1      ebsco  ebs100013422e  ... 2026-05-08 02:01:38.642847+00:00    None
2      ebsco  ebs100013424e  ... 2026-05-08 02:01:38.642847+00:00    None
3      ebsco     ebs100038e  ... 2026-05-08 02:01:38.642847+00:00    None
4      ebsco     ebs100068e  ... 2026-05-08 02:01:38.642847+00:00    None
5      ebsco     ebs100074e  ... 2026-05-08 02:01:38.642847+00:00    None
6      ebsco     ebs100094e  ... 2026-05-08 02:01:38.642847+00:00    None
7      ebsco     ebs100097e  ... 2026-05-08 02:01:38.642847+00:00    None
8      ebsco     ebs100231e  ... 2026-05-08 02:01:38.642847+00:00    None
9      ebsco     ebs100265e  ... 2026-05-08 02:01:38.642847+00:00    None
10     ebsco    ebs1002744e  ... 2026-05-08 02:01:38.642847+00:00    None
11     ebsco    ebs1002772e  ... 2026-05-08 02:01:38.642847+00:00    None
12     ebsco    ebs1002837e  ... 2026-05-08 02:01:38.642847+00:00    None
13     ebsco    ebs1002849e  ... 2026-05-08 02:01:38.642847+00:00    None
14     ebsco    ebs1003056e  ... 2026-05-08 02:01:38.642847+00:00    None
15     ebsco    ebs1003095e  ... 2026-05-08 02:01:38.642847+00:00    None
16     ebsco    ebs1003254e  ... 2026-05-08 02:01:38.642847+00:00    None
17     ebsco    ebs1003257e  ... 2026-05-08 02:01:38.642847+00:00    None
18     ebsco    ebs1003267e  ... 2026-05-08 02:01:38.642847+00:00    None
19     ebsco    ebs1003269e  ... 2026-05-08 02:01:38.642847+00:00    None

[20 rows x 6 columns]

axiell_adapter_table

   namespace             id  ...             last_modified deleted
0     axiell    collect:429  ... 2026-05-07 16:03:38+00:00   False
1     axiell   collect:1880  ... 2026-05-07 16:02:29+00:00   False
2     axiell   collect:9448  ... 2026-04-29 09:47:59+00:00   False
3     axiell  collect:10896  ... 2026-04-29 09:52:49+00:00   False
4     axiell      collect:1  ... 2026-04-28 14:06:12+00:00   False
5     axiell      collect:9  ... 2026-04-28 14:14:48+00:00   False
6     axiell   collect:1644  ... 2026-04-29 15:39:51+00:00   False
7     axiell   collect:1711  ... 2026-04-29 15:40:22+00:00   False
8     axiell   collect:1712  ... 2026-04-29 15:40:45+00:00   False
9     axiell   collect:1838  ... 2026-04-29 15:41:28+00:00   False
10    axiell   collect:1898  ... 2026-04-29 15:41:58+00:00   False
11    axiell   collect:2475  ... 2026-04-29 15:42:28+00:00   False
12    axiell   collect:2476  ... 2026-04-29 15:44:46+00:00   False
13    axiell   collect:9083  ... 2026-04-29 16:08:49+00:00   False
14    axiell   collect:9146  ... 2026-04-29 16:08:49+00:00   False
15    axiell   collect:9151  ... 2026-04-29 16:08:50+00:00   False
16    axiell   collect:9260  ... 2026-04-29 16:08:51+00:00   False
17    axiell  collect:12183  ... 2026-04-29 16:08:52+00:00   False
18    axiell  collect:15207  ... 2026-04-29 16:08:52+00:00   False
19    axiell   collect:2541  ... 2026-04-29 15:45:15+00:00   False

[20 rows x 6 columns]

folio_adapter_table

   namespace  ... deleted
0      folio  ...   False
1      folio  ...   False
2      folio  ...   False
3      folio  ...   False
4      folio  ...   False
5      folio  ...   False
6      folio  ...   False
7      folio  ...   False
8      folio  ...   False
9      folio  ...   False
10     folio  ...   False
11     folio  ...   False
12     folio  ...   False
13     folio  ...   False
14     folio  ...   False
15     folio  ...   False
16     folio  ...   False
17     folio  ...   False
18     folio  ...   False
19     folio  ...   False

[20 rows x 6 columns]

In [8]:
import xml.etree.ElementTree as ET

# Table to consult
example_table_name = "ebsco_adapter_table"
sample_table = tables.get(example_table_name)

# Extract an ID from the sampled dataset, preferring active rows with content
sample_df = table_samples.get(example_table_name)
eligible_rows = sample_df[
    sample_df["content"].notna()
    & sample_df["deleted"].astype("boolean").fillna(False).ne(True)
]

if eligible_rows.empty:
    raise ValueError(
        f"No non-deleted sample records with content are available in {example_table_name}"
    )

example_id = eligible_rows["id"].head(1).to_list()[0]
# example_id = "12345"

example_record = get_record_by_id(sample_table, example_id)
display(example_record)

xml_value = example_record["content"].to_pylist()[0]
if xml_value is None:
    raise ValueError(f"Record {example_id} has no XML content to display")

root = ET.fromstring(xml_value)
ET.indent(root)
ET.dump(root)

pyarrow.Table
namespace: large_string not null
id: large_string not null
content: large_string
changeset: large_string
last_modified: timestamp[us, tz=UTC]
deleted: bool
----
namespace: [["ebsco"]]
id: [["ebs115508527e"]]
content: [["<record xmlns="http://www.loc.gov/MARC21/slim"><leader>00000nas a22000003u 4500</leader><controlfield tag="001">ebs115508527e</controlfield><controlfield tag="003">EBZ</controlfield><controlfield tag="006">m     o  d  ||||||</controlfield><controlfield tag="007">cr|unu||||||||</controlfield><controlfield tag="008">260506|        xx uu p o     0    0||| d</controlfield><datafield tag="022" ind1=" " ind2=" "><subfield code="a">2979-1901</subfield></datafield><datafield tag="035" ind1=" " ind2=" "><subfield code="a">(EBZ)ebs115508527e</subfield></datafield><datafield tag="040" ind1=" " ind2=" "><subfield code="a">EBZ</subfield><subfield code="b">eng</subfield></datafield><datafield tag="042" ind1=" " ind2=" "><subfield code="a">msc</subfield></datafield><datafield tag="130" ind1="0" ind2=" "><subfield code="a">Economic History Series (Online)</subfield></datafield><datafield tag="245" ind1="1" ind2="0"><subfield code="a">Economic History Series</subfield><subfield code="h">[electronic resource].</subfield></datafield><datafield tag="773" ind1="0" ind2=" "><subfield code="t">JSTOR Arts &amp; Sciences I Archive Collection</subfield><subfield code="d">JSTOR</subfield></datafield><datafield tag="856" ind1="4" ind2="0"><subfield code="3">Full text available: 1926 - 1929.</subfield><subfield code="z">Available in JSTOR Arts &amp; Sciences I Archive Collection.</subfield><subfield code="u">https://www.jstor.org/journal/econhistseri</subfield></datafield><datafield tag="955" ind1=" " ind2=" "><subfield code="a">Journal</subfield><subfield code="2">ebsco-resource-type</subfield></datafield><datafield tag="955" ind1=" " ind2=" "><subfield code="a"/><subfield code="2">marc-source</subfield></datafield></record>"]]
changeset: [["de2e0ecf-4a81-11f1-96fd-fffbf987e35a"]]
last_modified: [[2026-05-08 02:01:38.642847Z]]
deleted: [[null]]

<ns0:record xmlns:ns0="http://www.loc.gov/MARC21/slim">
  <ns0:leader>00000nas a22000003u 4500</ns0:leader>
  <ns0:controlfield tag="001">ebs115508527e</ns0:controlfield>
  <ns0:controlfield tag="003">EBZ</ns0:controlfield>
  <ns0:controlfield tag="006">m     o  d  ||||||</ns0:controlfield>
  <ns0:controlfield tag="007">cr|unu||||||||</ns0:controlfield>
  <ns0:controlfield tag="008">260506|        xx uu p o     0    0||| d</ns0:controlfield>
  <ns0:datafield tag="022" ind1=" " ind2=" ">
    <ns0:subfield code="a">2979-1901</ns0:subfield>
  </ns0:datafield>
  <ns0:datafield tag="035" ind1=" " ind2=" ">
    <ns0:subfield code="a">(EBZ)ebs115508527e</ns0:subfield>
  </ns0:datafield>
  <ns0:datafield tag="040" ind1=" " ind2=" ">
    <ns0:subfield code="a">EBZ</ns0:subfield>
    <ns0:subfield code="b">eng</ns0:subfield>
  </ns0:datafield>
  <ns0:datafield tag="042" ind1=" " ind2=" ">
    <ns0:subfield code="a">msc</ns0:subfield>
  </ns0:datafield>
  <ns0:datafield tag="130" ind1="0" ind2=" ">
    <ns0:subfield code="a">Economic History Series (Online)</ns0:subfield>
  </ns0:datafield>
  <ns0:datafield tag="245" ind1="1" ind2="0">
    <ns0:subfield code="a">Economic History Series</ns0:subfield>
    <ns0:subfield code="h">[electronic resource].</ns0:subfield>
  </ns0:datafield>
  <ns0:datafield tag="773" ind1="0" ind2=" ">
    <ns0:subfield code="t">JSTOR Arts &amp; Sciences I Archive Collection</ns0:subfield>
    <ns0:subfield code="d">JSTOR</ns0:subfield>
  </ns0:datafield>
  <ns0:datafield tag="856" ind1="4" ind2="0">
    <ns0:subfield code="3">Full text available: 1926 - 1929.</ns0:subfield>
    <ns0:subfield code="z">Available in JSTOR Arts &amp; Sciences I Archive Collection.</ns0:subfield>
    <ns0:subfield code="u">https://www.jstor.org/journal/econhistseri</ns0:subfield>
  </ns0:datafield>
  <ns0:datafield tag="955" ind1=" " ind2=" ">
    <ns0:subfield code="a">Journal</ns0:subfield>
    <ns0:subfield code="2">ebsco-resource-type</ns0:subfield>
  </ns0:datafield>
  <ns0:datafield tag="955" ind1=" " ind2=" ">
    <ns0:subfield code="a" />
    <ns0:subfield code="2">marc-source</ns0:subfield>
  </ns0:datafield>
</ns0:record>

In [10]:
# Transform the record and print the transformed output

%reload_ext autoreload
%autoreload 2

import json
from adapters.transformers.ebsco_transformer import EbscoTransformer
from adapters.transformers.axiell_transformer import AxiellTransformer
from adapters.transformers.marcxml_transformer import MarcXmlTransformer
from adapters.utils.adapter_store import AdapterStore

table_to_transform = {
    "ebsco_adapter_table": EbscoTransformer,
    "axiell_adapter_table": AxiellTransformer,
    # "folio_adapter_table": FolioTransformer,  # TODO: Add when FOLIO transformer is implemented
}

if example_record is None or example_record.num_rows == 0:
    raise ValueError("No example record is loaded for transformation")

table = tables.get(example_table_name)
adapter_namespace = TABLE_NAMESPACES[example_table_name]

# Strictly not needed, unless we are triggering with a changeset
adapter_store = AdapterStore(table, namespace=adapter_namespace)
changeset_ids = ["dummy_changeset"]

transformer_class = table_to_transform.get(example_table_name)
if transformer_class is None:
    raise ValueError(f"No transformer configured for {example_table_name}")

# snapshot_id=None means "use the current snapshot"
transformer: MarcXmlTransformer = transformer_class(adapter_store, changeset_ids, snapshot_id=None)
transformed_record = list(transformer.transform(example_record.to_pylist()))
if not transformed_record:
    raise ValueError("Transformer produced no output for the selected record")

record_id, source_work = transformed_record[0]
print(f"Transformed record id: {record_id}")
print(json.dumps(source_work.model_dump(), indent=2))

Transformed record id: ebs115508527e
{
  "version": 1778205698,
  "type": "Visible",
  "data": {
    "title": "Economic History Series",
    "otherIdentifiers": [
      {
        "identifierType": {
          "id": "issn"
        },
        "ontologyType": "Work",
        "value": "2979-1901"
      }
    ],
    "alternativeTitles": [
      "Economic History Series (Online)"
    ],
    "format": {
      "id": "j",
      "label": "E-journals"
    },
    "description": null,
    "physicalDescription": null,
    "lettering": null,
    "createdDate": null,
    "subjects": [],
    "genres": [],
    "contributors": [],
    "thumbnail": null,
    "production": [],
    "languages": [],
    "edition": null,
    "notes": [],
    "duration": null,
    "items": [],
    "holdings": [
      {
        "note": null,
        "enumeration": [
          "Full text available: 1926 - 1929."
        ],
        "location": {
          "type": "DigitalLocation",
          "locationType": {
            "id": "online-resource"
          },
          "license": null,
          "accessConditions": [
            {
              "method": {
                "type": "ViewOnline"
              },
              "status": {
                "type": "LicensedResources",
                "relationship": {
                  "type": "Resource"
                }
              },
              "terms": null,
              "note": null
            }
          ],
          "url": "https://www.jstor.org/journal/econhistseri",
          "credit": null,
          "linkText": "Available in JSTOR Arts & Sciences I Archive Collection.",
          "createdDate": null
        }
      }
    ],
    "collectionPath": null,
    "referenceNumber": null,
    "imageData": [],
    "workType": "Standard",
    "currentFrequency": null,
    "formerFrequency": [],
    "designation": []
  },
  "state": {
    "sourceIdentifier": {
      "identifierType": {
        "id": "ebsco-alt-lookup"
      },
      "ontologyType": "Work",
      "value": "ebs115508527e"
    },
    "sourceModifiedTime": "2026-05-08T02:01:38.642847Z",
    "relations": {
      "ancestors": [
        {
          "title": "JSTOR Arts & Sciences I Archive Collection",
          "workType": "Series",
          "depth": 0,
          "numChildren": 0,
          "numDescendents": 0
        }
      ]
    },
    "internalWorkStubs": [],
    "mergeCandidates": [],
    "modifiedTime": "2026-05-08T09:52:51.027996Z"
  },
  "redirectSources": []
}

In [ ]:
from datetime import datetime
from pathlib import Path

# Backup and delete utilities for pyiceberg tables

BACKUP_DIR = Path("./data/backups")


def _assert_table_mutation_allowed(operation: str) -> None:
    if USE_REST_API_TABLE and not ALLOW_REMOTE_TABLE_MUTATIONS:
        raise RuntimeError(
            f"{operation} is blocked because USE_REST_API_TABLE=True. "
            "Set ALLOW_REMOTE_TABLE_MUTATIONS=True only if you intentionally want to modify remote REST API tables."
        )


def backup_table(table, table_name: str) -> Path:
    """Backup all rows from a table to a parquet file in ./data/backups."""
    BACKUP_DIR.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    backup_path = BACKUP_DIR / f"{table_name}_{timestamp}.parquet"

    # Scan all data and write to parquet
    arrow_table = table.scan().to_arrow()
    row_count = arrow_table.num_rows
    if row_count == 0:
        print(f"Table '{table_name}' is empty, nothing to backup.")
        return backup_path

    import pyarrow.parquet as pq

    pq.write_table(arrow_table, backup_path)
    print(f"Backed up {row_count} rows to: {backup_path}")
    return backup_path


def restore_backup(table, backup_path: str | Path) -> int:
    """Restore rows from a parquet backup file to the table."""
    _assert_table_mutation_allowed("restore_backup")

    import pyarrow.parquet as pq

    backup_path = Path(backup_path)
    if not backup_path.exists():
        raise FileNotFoundError(f"Backup file not found: {backup_path}")

    arrow_table = pq.read_table(backup_path)
    row_count = arrow_table.num_rows
    if row_count == 0:
        print("Backup file is empty, nothing to restore.")
        return 0

    table.append(arrow_table)
    print(f"Restored {row_count} rows from: {backup_path}")
    return row_count


def list_backups(table_name: str | None = None) -> list[Path]:
    """List available backup files, optionally filtered by table name."""
    if not BACKUP_DIR.exists():
        return []
    backups = sorted(BACKUP_DIR.glob("*.parquet"), reverse=True)
    if table_name:
        backups = [b for b in backups if b.name.startswith(f"{table_name}_")]
    for b in backups:
        print(f"  {b.name}")
    return backups


def delete_all_rows(table, table_name: str, *, backup: bool = True, dry_run: bool = False):
    """Delete all rows from a table, with optional backup first.

    Args:
        table: The pyiceberg table to delete from.
        table_name: Name used for backup file prefix.
        backup: If True, backup the table before deleting.
        dry_run: If True, perform backup but skip the actual deletion.
    """
    _assert_table_mutation_allowed("delete_all_rows")

    from pyiceberg.expressions import AlwaysTrue

    before_count = table.scan().count()
    print(f"Rows before delete: {before_count}")

    if before_count == 0:
        print("Table is already empty, nothing to delete.")
        return

    if backup:
        backup_table(table, table_name)

    if dry_run:
        print("[DRY RUN] Skipping deletion. Backup was created if enabled.")
        return

    with table.transaction() as tx:
        try:
            tx.delete(delete_filter=AlwaysTrue())
        except Exception as e:
            raise RuntimeError("Row-level delete failed.") from e

    after_count = table.scan().count()
    print(f"Rows after delete:  {after_count}")
    assert after_count == 0, "Delete operation failed: table not empty"
    print("All rows deleted successfully via row-level delete.")

# Example usage:
table_to_target_name = "axiell_adapter_table"
table_to_target = tables.get(table_to_target_name)

# Set dry_run=False to actually delete
# delete_all_rows(table_to_target, table_to_target_name, backup=True, dry_run=True) 
# list_backups(table_to_target_name)
# restore_backup(table_to_target, f"./data/backups/{table_to_target_name}_20260115_155259.parquet")